### ISSUE TITLE
vendor配下になんか残っている

### ISSUE THREAD

**Issue by kondog** [MYamashii/WeatherReport#126]
お世話になっております、近藤といいます。

貴重な休日の午前を目一杯使い動作させてみました。
今日の福岡の天気は晴れということでなんか動作しているみたいです。

さて表題の件ですが、vendor配下に多分bundle installした
残骸が残っていますので、こちらは消去した方がいいのでは
ないかと思いissueを挙げさせて頂きました。

ついでにvendor/bundler配下を.gitignoreに追加した方が
いいような気もします。

個人用PJっぽいのでまあ別にどうでもいいところではありますが。

宜しくおねがいします。
以上です。

**Comment by MYamashii** [comment]
ご連絡ありがとうございます。
ご指摘の通り、不要なファイルが残っているようです。
このファイルの削除、.gitignoreへの追加を行います。

**Comment by MYamashii** [comment]
フォルダ削除、.gitignoreへの追加を行いました。
他ご指摘ありますでしょうか？

**Comment by kondog** [comment]
いんじゃないでしょうか！！
